[package]
name = "rustcdp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.116"
serde = { version = "1.0.200", features = ["derive"] }
rand = "0.9.0-alpha.2"
url = "2.5.2"
tungstenite = "0.23.0"

log = "0.4.22"

derive_more = { version = "1.0.0-beta.7", features = ["from"]}